name: Run API Tests
on:
 push:
  branches: [main]
 workflow_dispatch: 
 schedule:
  - cron: '30 2 * * *' #8:00 AM IST
  - cron: '30 13 * * *' #7:00 PM IST

jobs:
 run-tests:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
         node-version: '18'

    - name: Install newman
      run:
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Collection
      run:
         newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \
         -e QACopy.postman_environment.json \
         -r cli,htmlextra 

    - name: Upload Report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
       name: newman-html-report
       path: newman/*.html
         

        
        
    
